// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using model.DbContext;

#nullable disable

namespace model.Migrations
{
    [DbContext(typeof(FiscusDbContext))]
    [Migration("20250305140720_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("model.Entities.Invoice", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<int>("IssuedById")
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.HasKey("Code", "IssuedById");

                    b.HasIndex("IssuedById");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("model.Entities.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("organisations");
                });

            modelBuilder.Entity("model.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("position_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceOrgId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceCode", "InvoiceOrgId");

                    b.ToTable("positions");
                });

            modelBuilder.Entity("model.Entities.Invoice", b =>
                {
                    b.HasOne("model.Entities.Organisation", "IssuedBy")
                        .WithMany("Invoices")
                        .HasForeignKey("IssuedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedBy");
                });

            modelBuilder.Entity("model.Entities.Position", b =>
                {
                    b.HasOne("model.Entities.Invoice", "Invoice")
                        .WithMany("Positions")
                        .HasForeignKey("InvoiceCode", "InvoiceOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("model.Entities.Invoice", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("model.Entities.Organisation", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
