// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using model.DbContexts;

#nullable disable

namespace model.Migrations
{
    [DbContext(typeof(FiscusDbContext))]
    partial class FiscusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("model.Entities.Invoice", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssuedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Paid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Code", "IssuedById");

                    b.HasIndex("IssuedById");

                    b.HasIndex("RecipientId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("model.Entities.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("model.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceOrgId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceCode", "InvoiceOrgId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("model.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipient");
                });

            modelBuilder.Entity("model.Entities.Invoice", b =>
                {
                    b.HasOne("model.Entities.Organisation", "IssuedBy")
                        .WithMany("Invoices")
                        .HasForeignKey("IssuedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("model.Entities.Recipient", "Recipient")
                        .WithMany("Invoices")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssuedBy");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("model.Entities.Position", b =>
                {
                    b.HasOne("model.Entities.Invoice", "Invoice")
                        .WithMany("Positions")
                        .HasForeignKey("InvoiceCode", "InvoiceOrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("model.Entities.Invoice", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("model.Entities.Organisation", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("model.Entities.Recipient", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
